# Generated by Django 3.1.2 on 2020-10-14 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=None, max_length=36)),
                ('vehicle_type', models.CharField(choices=[('TWO_WHEELER', 'Two wheeler'), ('THREE_WHEELER', 'Three wheeler'), ('FOUR_WHEELER', 'Four wheeler')], max_length=13)),
                ('chase_no', models.CharField(default=None, max_length=36)),
                ('engine_no', models.CharField(default=None, max_length=36)),
                ('reg_no', models.CharField(default=None, max_length=36)),
                ('manufacturer', models.CharField(default=None, max_length=36)),
                ('model', models.CharField(default=None, max_length=36)),
                ('fuel', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric')], max_length=8)),
                ('no_of_passengers', models.IntegerField(blank=True, default=0, null=True)),
                ('wheel_base', models.CharField(default=None, max_length=36)),
                ('cubic_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('manufacturer', 'model')},
            },
        ),
    ]
