# Generated by Django 3.1.2 on 2020-10-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
